FROM        ubuntu:16.04
MAINTAINER  dev@azelf.com

ENV         LANG C.UTF-8

RUN         apt-get -y update

## uWGSI install
#RUN         pip install uwsgi
#
## Nginx install
#RUN         apt-get -y install nginx
#
## supervisor install
#RUN         apt-get -y install supervisor
